# Change these first
owner: quanhieu # Your GitHub organization or username, where this repository lives
repo: alive_up # The name of this repository

sites:
  # Blog tech    
  - name: Pikalog
    url: https://kipalog.com/
  - name: Viblo
    url: https://viblo.asia/followings
  - name: devto
    url: https://dev.to/
  - name: dailydev
    url: https://app.daily.dev/
  - name: patternsJs
    url: https://www.patterns.dev
  - name: refactoring
    url: https://refactoring.guru/design-patterns
  - name: giaosucan
    url: https://www.giaosucan.com/
  - name: niviki
    url: https://www.niviki.com
  - name: duyet
    url: https://blog.duyet.net/
  - name: medium
    url: https://medium.com/
  - name: cuongquach
    url: https://cuongquach.com/
  - name: shipit
    url: https://shipit.dev/posts/kubernetes-overview-diagrams.html
  - name: cloudnativeviet
    url: https://www.cloudnativeviet.net/documents/kubernetes/
  - name: xuanthulab
    url: https://xuanthulab.net/
  - name: anonystick - Tips Javascript
    url: https://anonystick.com/
  - name: guru99
    url: https://www.guru99.com/
  - name: dnsimple
    url: https://dnsimple.com/comics
  - name: howhttps
    url: https://howhttps.works/
  - name: wizardzines
    url: https://wizardzines.com/comics/
  # - name: 
  #   url: 

  # Anime 
  - name: Ani 47
    url: https://anime47.com/
  - name: Ani pro
    url: http://animevietsub.pro/
    expectedStatusCodes:
      - 200
      - 403
      - 503
  - name: Ani tvn
    url: https://animetvn.info/
  - name: Ani 4u
    url: https://ani4u.org/
  - name: Ani Vuighe
    url: https://vuighe.net/
    __dangerous__disable_verify_host: true
  - name: Ani clip
    url: https://clipanime.com/
  - name: Ani pops
    url: https://pops.vn/anime
  - name: Ani muse
    url: https://www.youtube.com/@MuseVietnam/featured
  # - name: 
  #   url: 
    
  # Fansub    
  - name: clip-sub
    url: https://clip-sub.com/
  - name: yami-sora
    url: https://www.yami-sora.org/
  - name: relieftranslation
    url: https://relieftranslation.com/anime/
    expectedStatusCodes:
      - 200
      - 403
      - 503
  - name: Yoakefs
    url: https://yoakefs.com/
  - name: kanefusafs
    url: https://www.kanefusafs.net/
  - name: kimi
    url: https://kimi-fansub.blogspot.com/
  - name: smfs
    url: https://sm-f.blogspot.com/
  - name: a4vf
    url: https://a4vf.com/
  - name: koga
    url: http://koga-fansub.net/
  - name: vnfs
    url: https://vnfs-team.com/
  - name: cabfansub
    url: https://cabfansub.com/
  - name: crazysol
    url: https://crazysol.blogspot.com/
  - name: zingfansub
    url: https://zingfansub.ws/zfs/
  - name: olshiro
    url: http://olshiro.net/load/vietsub/10
  - name: yureisub
    url: https://www.yureisub.com/
  - name: ashirogifs
    url: https://ashirogifs.blogspot.com/
  - name: jikanfansub
    url: https://jikanfansub.wordpress.com/
  - name: vnjp - doremonfs
    url: http://www.vnjp.us/
  - name: wakanafs
    url: https://wakanafs.blogspot.com/
  - name: waya
    url: http://waya.itea.vn/
  - name: nyaafs
    url: http://nyaa-fansub.net/
    expectedStatusCodes:
    - 200
    - 403
    - 503
  - name: conanvnfansub
    url: https://conanvnfansub.wordpress.com/
  - name: vnkeyfc
    url: https://vnkeyfc.com/
  - name: otakumano
    url: https://otakumano4fan.blogspot.com/
  - name: pokemonviet
    url: https://pokemonviet.com/
  - name: a4vf
    url: https://a4vf.net/
  - name: Nishiro Fansub
    url: https://www.notion.so/Animulism-342a41414b0b43c9aa5b10e242f718a1
  # - name: 
  #   url: 
    
  # Live action    
  - name: nekofansub
    url: https://nekofansubblog.wordpress.com/
  - name: flyfansub
    url: https://flyfansub.blogspot.com/
  - name: luclacmeo
    url: https://luclacmeo.wordpress.com/
  - name: mochifansub
    url: https://mochifansub.home.blog/
  - name: relnguyen
    url: https://relnguyen.blogspot.com/
  - name: unmeifs
    url: https://unmeifs.blogspot.com/
  - name: Haruki Fansub
    url: https://www.facebook.com/profile.php?id=100064495554663
  - name: futarisubteam
    url: https://futarisubteam.wordpress.com/
  - name: amechanfansub
    url: https://amechanfansub.wordpress.com/
  - name: kokocon
    url: http://fansub.kokocon.net/
  # - name: 
  #   url: 
    
  # Light novel    
  - name: Hako
    url: https://ln.hako.vn/
  - name: Hako again
    url: https://docln.net/
  - name: shinigamilnteam
    url: https://shinigamilnteam.com/
    __dangerous__disable_verify_host: true
  - name: baka-tsuki
    url: https://www.baka-tsuki.org/project/index.php?title=Category:Light_novel_(Vietnamese)
  - name: valvrareteam
    url: http://valvrareteam.com/
  - name: sonako
    url: https://sonako.fandom.com/vi/wiki/Sonako_Light_Novel
  - name: otakusan
    url: https://otakusan.net/LightNovel
  - name: meobietbay
    url: https://meobietbay.com/overlord/
  - name: thatnovelcorner
    url: https://thatnovelcorner.com/light-novels/
  - name: novelupdates
    url: https://www.novelupdates.com/
    expectedStatusCodes:
    - 200
    - 403
    - 503
  - name: dwrteam
    url: https://dwrteam.blogspot.com/
  - name: zennomi
    url: https://zennomi.fandom.com/wiki/Zennomi_Wiki
  - name: Zennomi
    url: https://www.facebook.com/Zennomi
  - name: Zennomi again
    url: https://zenno.moe/
  - name: Đứa biết nhiều nhất về Light Novel ở Việt Nam
    url: https://www.facebook.com/NaviRanobe/
  # - name: 
  #   url: 
    
  # Film    
  - name: Xemphim club
    url: https://xemphim.club/
  - name: Xemphim club again
    url: https://phimtea.com/
  # - name: 
  #   url: 
    
  # Torrent    
  - name: kokocon
    url: https://tracker.kokocon.net/
  # - name: nyaa se
  #   url: https://sukebei.nyaa.si/
    
  # 4rum    
  - name: Ve o zet
    url: https://voz.vn/
    expectedStatusCodes:
    - 200
    - 403
    - 503
  - name: vnsharing
    url: https://vnsharing.vn/
    expectedStatusCodes:
    - 200
    - 403
    - 503
  - name: vnsharing again
    url: https://vnsharing.site/
  - name: anime-sharing
    url: https://www.anime-sharing.com/forum/
  - name: kokocon
    url: http://kokocon.net/
  - name: hako.re
    url: https://mangochan.site/
  - name: myanimelist
    url: https://myanimelist.net/
  - name: anime-planet
    url: https://www.anime-planet.com/
  # - name: 
  #   url: 
    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /alive_up
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  theme: ocean # light, dark, night or ocean
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a repo check pages are alive **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
      # href: https://$OWNER.github.io/$REPO
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  # workflowSchedule:
  #   graphs: "0 0 * * *"
  #   responseTime: "0 23 * * *"
  #   staticSite: "0 1 * * *"
  #   summary: "0 0 * * *"
  #   updateTemplate: "0 0 * * *"
  #   updates: "0 3 * * *"
  #   uptime: "0 */1 * * *"

# commitMessages:
#   commitAuthorName: "aliveup-bot"
#   commitAuthorEmail: "aliveup-bot@users.noreply.github.com"

# user-agent: aliveup-bot

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
